version: '3.8'

services:
  shl-recommender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shl_recommender_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/workspace/app
      - ./data:/workspace/data
      - ./frontend:/workspace/frontend
      - ./tests:/workspace/tests
    environment:
      - DEBUG=true
    restart: unless-stopped
